/* SHIELD — Supporting pages (Manufacturing / Experiments / Analytics / Passport / Alerts) */

function card(title, rowsHtml, body = '') {
  return `<div class="ph-card"><h3>${title}</h3>${rowsHtml ? rowsHtml : ''}${body}</div>`;
}
function stat(l, v) { return `<div class="stat"><span class="l">${l}</span><span class="v">${v}</span></div>`; }

export function createPlaceholderPage(host, kind) {
  const page = document.createElement('div');
  page.className = 'ph';
  host.appendChild(page);

  const content = {
    manufacturing: {
      title: 'Manufacturing Line',
      lead: 'Digital-twin-connected production line state for instrumented EV-CH-007 builds.',
      cards: card('Line State', stat('Line', 'RUNNING') + stat('Station 4 · Sensor bonding', 'SG01–SG04 done') + stat('Edge node flash', 'v0.9.2 verified') + stat('Shadow twin sync', 'ACTIVE')),
      body: `<div class="ph-card"><h3>Wireless Acquisition Test</h3><p>Throughput of MQTT packets from edge node to twin core during line qualification.</p><div class="bars" style="height:70px">${'<i style="height:45%"></i><i style="height:70%"></i><i style="height:55%"></i><i style="height:80%"></i><i style="height:62%"></i><i style="height:90%"></i><i style="height:75%"></i>'.repeat(3)}</div></div>`,
    },
    experiments: {
      title: 'Experiments',
      lead: 'Controlled load-case experiments executed against the physical prototype.',
      cards: card('Last Experiment · EX-014', stat('Load case', 'Battery inertial · 15 kg') + stat('Applied force', '147 N @ +Z') + stat('Peak strain (B4)', '78 µε') + stat('Status', 'COMPLETE')),
      body: `<div class="ph-card"><h3>Pending</h3><p>EX-015 · rear torsion sweep<br>EX-016 · curb impact pulse 15 g<br>EX-017 · thermal cycling with strain compensation validation</p></div>`,
    },
    analytics: {
      title: 'Analytics',
      lead: 'Signal analytics across the monitored regions (prototype data volume).',
      cards: card('Strain residual distribution', stat('µε (mean abs)', '2.4') + stat('Max residual', '26 µε @ SG04') + stat('RMS trend', '+0.3 µε / day') + stat('Baseline drift (temp-corrected)', '−1.1 µε')),
      body: `<div class="ph-card"><h3>Two-IMU Transfer</h3>${stat('RMS ratio R/F', '0.61') + stat('Dominant freq shift', '−4.5 Hz') + stat('Transmission', '61 %')}</div>`,
    },
    passport: {
      title: 'Asset Passport',
      lead: 'As-built digital passport for the instrumented prototype.',
      cards: card('EV-CH-007', stat('Build', '1 : 4 instrumented model') + stat('Battery pack', 'Central floor · 15 kg eq.') + stat('Regions', 'B1–B4, F1, C1, R1') + stat('Edge node', 'SHIELD EDGE1 (ESP32)')),
      body: `<div class="ph-card"><h3>Sensor Roster</h3><p>SG01 SG02 SG03 SG04 · IMU01 IMU02 · LC01 · TEMP01 · DISP01<br><br>Sensor layout is vehicle-specific — generated from configuration for production placement.</p></div>`,
    },
    alerts: {
      title: 'Alerts',
      lead: 'Operational notifications generated by the twin and its hardware front-end.',
      cards: card('Current', stat('SG02 OFFLINE', 're-validate channel') + stat('B4 residual alert', '+26 µε · review') + stat('Edge link', 'stable · 41 ms RTT')),
      body: `<div class="ph-card"><h3>Policy</h3><p>A sensor failure never flags a structural zone as failed — the zone assessment is suspended and marked for review until the channel is re-validated.</p></div>`,
    },
  }[kind] || { title: kind, lead: '', cards: '', body: '' };

  page.innerHTML = `<h2>${content.title}</h2><div class="lead">${content.lead}</div><div class="ph-grid">${content.cards}${content.body}</div>`;
  return page;
}